### ISSUE TITLE
Infinite loop in RPPIP

### ISSUE THREAD

**Issue by abhikr360** [mkbera/utilities#1]
Once flag is set to be true, it never becomes false. So after running n_proc programs, the code gets stuck in a while loop

**Comment by mkbera** [comment]
Please use `run_parallel_progs_in_threads as RPPIT` for now. I am working on fixing the bug.

**Comment by mkbera** [comment]
Fixed the bug. Processes do not share normal variables. They need special variables for sharing between processes.
